### PR TITLE
Add compression support

### PR DESCRIPTION
**Pull request by mooman219**
Add basic gzip transport encoding support to chunked streaming uploads.

### CODE REVIEW

**Comment by vilasj** [comment]
Thanks for the pull request. Tests seem to be failing in Travis. Please take a look.

**Comment by mooman219** [comment]
Oh darn, compatibility issues with python 3. I'll check it out

**Comment by mooman219** [comment]
Gzip.py is a _mostly_ as is port from CPython 3.4 to work in 2.7/3+. It fixes a streaming bug that exists in python 2.7 and is required for streams that don't support tell() and seek(). I don't see a point if fixing the lints as I would rather keep minimal diffs.

**Comment by houglum** [comment]
LGTM - I agree with keeping the source that was ported from CPython as-is (as much as possible) to enable easier merging in the future, if needed.

**Comment by houglum** [comment]
Hmm... GitHub didn't give me the option to squash the 10 commits into one.  I'll pull in the repo, fix it, and force push.

**Pull request merged**
