### PR TITLE
Fix uploads for non-seekable streams

### PR DESCRIPTION
**Pull request by mwitkow-io**
Fixes https://github.com/google/apitools/issues/18

### CODE REVIEW

**Comment by mwitkow-io** [comment]
I signed it!

**Comment by mwitkow-io** [comment]
Or at least our company did "Improbable Worlds Ltd"

**Comment by craigcitro** [comment]
this looks good -- just want to ask @thobrla to confirm that this is unlikely to quietly break anything for gsutil?

**Comment by thobrla** [comment]
Looks good.

Note: we use seekable() elsewhere but that only applies to IOBase objects, which is not applicable for upload streams with type 'file'.

**Comment by craigcitro** [comment]
awesome -- thanks @mwitkow-io!

**Pull request merged**
