### PR TITLE
Tolerate remappings if the mapped value is the same.

### PR DESCRIPTION
**Pull request by vilasj**

### CODE REVIEW

**Comment by craigcitro** [comment]
(googlebot wants you to join the google org)

**Comment by craigcitro** [comment]
can you add a quick test?

**Comment by vilasj** [comment]
Added a test. Craig, let me know if there is something appropriate that I can assert at the end of the test.

**Comment by craigcitro** [comment]
that looks good -- you could always have an assertion to confirm it still fails on a new remapping?

**Comment by craigcitro** [comment]
LGTM in any event, you can merge either before or after another test as you prefer :wink:

**Pull request merged**
