### PR TITLE
Handle encoded response content in batch http request in Python 3

### PR DESCRIPTION
**Pull request by markflyhigh**
Fix issue reported in https://github.com/google/apitools/issues/249.

The problem happens in Python 3 when execute a http request and encoded content is returned. This breaks `email_parser.Parser().parsestr()` call in `batch.py` since the function argument only accepted `str` (not bytes). There is a callback `__ProcessHttpResponse` that handles encoded response content but the call happens later.

### CODE REVIEW

**Comment by markflyhigh** [comment]
friendly ping.

**Comment by kevinli7** [comment]
When I test this out manually in gcloud, this line in batch.py is failing in python2:
mime_response = parser.parsestr(header + content)

Also, I feel like this decoding should have some sort of switch to turn it on and off.

**Comment by markflyhigh** [comment]
Interesting. The unit tests are passing in Python 2 and 3. Can you give more details how you test with gcloud?

Add a switch to this decoding sounds good to me. I think we can add a `response_encoding` field to `BatchHttpRequest` and `BatchApiRequest`, which also allow people to specify the encoding of the response content.

**Comment by markflyhigh** [comment]
@kevinli7 PTAL

**Comment by kevinli7** [comment]
LGTM. @houglum not sure if you guys use batch? Do you want to take a look as well?

**Pull request merged**
