### PR TITLE
Cleanup some dead test code.

### PR DESCRIPTION
**Pull request by craigcitro**
It turns out an ancient refactor (merging the gsutil fork) turned some tests
into dead code; I noticed that something was awry when the GCE header name was
updated but tests didn't fail.

The fix was easy (just drop the dead code and add something new), and I bumped
up coverage a wee bit in the process. (It'd be easy to keep going, but I hate
mocks, and think most of these tests have little value.)

Closes #90 (via different means).

PTAL @thobrla

### CODE REVIEW

**Comment by thobrla** [comment]
LGTM

**Comment by Galabar001** [comment]
I think the ComputeEngineCredentials.java and MockMetadataServerTransport.java files are out-of-sync internally.

Where should changes be made (in google3/ or on github)?

**Comment by craigcitro** [comment]
@Galabar001 wrong repo? :wink:

**Comment by Galabar001** [comment]
Garr!!! :)  So many things to change, so many incorrect repos to spam. :(

**Pull request merged**
